#!/bin/bash

# Shell script to build and install one or more
# builds of the comserv3 system.

if [[ $# > 0 ]] ; then
    argv=$*
else
    argv=(32 64)
fi

for nb in ${argv[@]} ; do

    export NUMBITS=$nb
    echo NUMBITS=$NUMBITS

    BINDIR=bin.$NUMBITS
    SUFFIX=`egrep DCOMSERV2 Makefile.include | fgrep -v '#'`
    if [[ ! -z $SUFFIX ]] ; then \
	echo $SUFFIX
	SUFFIX=cs2_compat
	BINDIR=$BINDIR.$SUFFIX
    fi

    rm -rf $BINDIR

    echo make clean ...
    make clean >& /dev/null

    logfile=make.$NUMBITS.log
    errfile=make.$NUMBITS.err
    echo make ...
    make >& $logfile
    egrep -i "(error)|(warning)" $logfile | grep -v Werror > $errfile
    echo $errfile errors = `cat $errfile | wc -l`

    logfile=install.$NUMBITS.log
    errfile=install.$NUMBITS.err
    echo make install BINDIR=$BINDIR ...
    make install BINDIR=$BINDIR >& $logfile
    egrep -i "(error)|(warning)" $logfile | grep -v Werror > $errfile
    echo $errfile errors = `cat $errfile | wc -l`

done
